name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init
        run: cd website
      - name: Git config
        run: |
          git config --global user.name github-actions[bot] 
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Write English translations
        run: yarn run write-translations
      - name: crowdin action
        uses: crowdin/github-action@1.4.8
        with:
          upload_sources: true
          download_translations: true
          download_language: ['zh-CN', 'ru']
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - name: Publish to GitHub Pages
        run: GIT_USER=github-actions[bot] yarn run publish-gh-pages
