name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --global user.name github-actions[bot] 
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: 'website'
      - name: Write English translations
        run: yarn run write-translations
        working-directory: 'website'
      
